### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJTest.jl#6]

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- [ ] (**breaking**) Add `:accelerated_evaluation`, `:stack_evaluation` and `:accelerated_stack_evalution` tests.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- (**breaking**) Add `:accelerated_evaluation`, `:stack_evaluation` and `:accelerated_stack_evalution` tests.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**Code organisation**). Refactor code to make new package MLJTestInterface.jl the foundation (#27)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**Code organisation**). Refactor code to make new package MLJTestInterface.jl the foundation (#27)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new feature**) Add a method `test(model; options...)` for testing a single model using multiple, *inferred* datasets.
- (**breaking**) Remove `test_single_target_classifiers`, `test_single_target_regressors`,  `test_single_target_count_regressors`,  `test_continuous_table_transformers`.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new feature**) Add a method `test(model; options...)` for testing a single model using multiple, *inferred* datasets.
- (**breaking**) Remove `test_single_target_classifiers`, `test_single_target_regressors`,  `test_single_target_count_regressors`,  `test_continuous_table_transformers`.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
